steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/student-ml', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/student-ml']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - student-ml
      - --image=gcr.io/$PROJECT_ID/student-ml
      - --region=europe-west1
      - --platform=managed

options:
  logging: CLOUD_LOGGING_ONLY